name: Kubernetes deployment
on:
  workflow_call:
    inputs:
      deploymentTarget:
        required: true
        type: string
      prNumber:
        required: false
        type: number
      tag:
        required: false
        type: string
    secrets:
      KUBE_CONFIG: 
        required: true

env:
  BASE_HOST: sendit.ga

jobs:
  setup-k8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache Kustomize
        id: cache
        uses: actions/cache@v2
        with:
          path: kustomize
          key: kustomize
      - name: Set up Kustomize
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v4.5.1/kustomize_4.5.1_linux_amd64
          chmod u+x ./kustomize

  pr-deployment:
    if: ${{ inputs.deploymentTarget == 'pr' }}
    runs-on: ubuntu-latest
    needs: [setup-k8]
    steps:
      - uses: actions/checkout@v2
      - name: Cache Kustomize
        id: cache
        uses: actions/cache@v2
        with:
          path: kustomize
          key: kustomize
      - run: |
          ls -la
          node scripts/generate-kustomization.js $PWD/scripts/kustomization.yaml.sample $PWD/manifests/overlays/pr/kustomization.yaml pr-${{ inputs.prNumber }}-preview
          node scripts/replace.js pr-${{ inputs.prNumber }}.preview. /spec/rules/0/host ${{ env.BASE_HOST }} $PWD/manifests/overlays/pr/ingress.json
          node scripts/replace.js pr-${{ inputs.prNumber }}-preview /metadata/namespace "" $PWD/manifests/overlays/pr/ingress-namespace.json
          node scripts/replace.js pr-${{ inputs.prNumber }}-preview /metadata/name "" $PWD/manifests/overlays/pr/namespace.json
          ./kustomize build $PWD/manifests/overlays/pr

  staging-deployment:
    if: ${{ inputs.deploymentTarget == 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.registry_package.package.package_version.release.tag_name }}

  prod-deployment:
    if: ${{ inputs.deploymentTarget == 'production' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.registry_package.package.package_version.release.tag_name }}