name: Kubernetes deployment
on:
  workflow_call:
    inputs:
      deploymentTarget:
        required: true
        type: string
      prNumber:
        required: false
        type: number
      tag:
        required: false
        type: string
jobs:
  setup-k8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Kustomize
        run: |
          curl -o kustomize --location https://github.com/kubernetes-sigs/kustomize/releases/download/v4.5.1/kustomize_4.5.1_linux_amd64
          chmod u+x ./kustomize
  pr-deployment:
    if: ${{ inputs.deploymentTarget == 'pr' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.prNumber }}
  # staging-deployment:
  #   if: ${{ inputs.deploymentTarget == 'staging' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ${{ github.event.registry_package.package.package_version.release.tag_name }}
  # prod-deployment:
  #   if: ${{ inputs.deploymentTarget == 'production' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ${{ github.event.registry_package.package.package_version.release.tag_name }}